name: compile

on:
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  update_tex:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Git repository
        uses: actions/checkout@v4
      
      - name: Install LaTeX (texlive full)
        run: |
          sudo apt-get install texlive-full

      - name: Compile LaTeX document
        run: |
          ./build.sh 2

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes to git
        run: |
          git add -f qm1_notes.pdf
          git commit -m "[bot] update qm1_notes.pdf"
          git status
          git push

